/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package intergraf;

import dominio.Origami;
import gerTarefas.FuncoesUteis;
import gerTarefas.GerInterGrafica;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;

/**
 *
 * @author LEDS
 */
public class DlgGerenciarOrigami extends javax.swing.JDialog {

    private GerInterGrafica gerIG;
    /**
     * Creates new form DlgGerenciarOrigami
     */
    public DlgGerenciarOrigami(java.awt.Frame parent, boolean modal, GerInterGrafica gerIG) {
        initComponents();
        this.gerIG = gerIG;
        limparCampos();
        panelEvento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbPanOrigami = new javax.swing.JTabbedPane();
        panNovo = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        dific1 = new javax.swing.JLabel();
        boxDificuldade = new javax.swing.JComboBox<>();
        lblPreco = new javax.swing.JLabel();
        spnPreco = new javax.swing.JSpinner();
        lblFoto = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        spnQtdPecas = new javax.swing.JSpinner();
        lblQtdPecas = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        boxTipoPapel = new javax.swing.JComboBox<>();
        boxVariacao = new javax.swing.JComboBox<>();
        dific2 = new javax.swing.JLabel();
        panelMateriais = new javax.swing.JPanel();
        chkTassel = new javax.swing.JCheckBox();
        chkPompom = new javax.swing.JCheckBox();
        chkPisca = new javax.swing.JCheckBox();
        chkVerniz = new javax.swing.JCheckBox();
        chkCola = new javax.swing.JCheckBox();
        chkNylon = new javax.swing.JCheckBox();
        chkBijuteria = new javax.swing.JCheckBox();
        chkMandala = new javax.swing.JCheckBox();
        chkOutros = new javax.swing.JCheckBox();
        chkBarbante = new javax.swing.JCheckBox();
        btnAdicionar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        panModular = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbModular = new javax.swing.JTable();
        editarMod = new javax.swing.JButton();
        ExcluirMod = new javax.swing.JButton();
        panArquit = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbArquit = new javax.swing.JTable();
        EditarArq = new javax.swing.JButton();
        ExcluirArq = new javax.swing.JButton();
        panBlock = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbBlock = new javax.swing.JTable();
        EditarBlock = new javax.swing.JButton();
        ExcluirBlock = new javax.swing.JButton();
        panBill = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbBill = new javax.swing.JTable();
        EditarBill = new javax.swing.JButton();
        ExcluirBill = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciador de Origamis");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbPanOrigami.setBackground(new java.awt.Color(132, 220, 240));
        tbPanOrigami.setForeground(new java.awt.Color(255, 255, 255));
        tbPanOrigami.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tbPanOrigami.setToolTipText("");
        tbPanOrigami.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N

        panNovo.setToolTipText("");
        panNovo.setOpaque(false);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Detalhes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel13.setForeground(new java.awt.Color(204, 204, 204));
        jPanel13.setOpaque(false);

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNome.setText("Nome");

        dific1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dific1.setText("Dificuldade");

        boxDificuldade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        boxDificuldade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Principiante", "Intermediário", "Avançado" }));

        lblPreco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPreco.setText("Preço");

        spnPreco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spnPreco.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.25d));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(18, 18, 18)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(dific1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boxDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(lblPreco)
                        .addGap(18, 18, 18)
                        .addComponent(spnPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dific1)
                    .addComponent(boxDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPreco))
                .addContainerGap())
        );

        lblFoto.setBackground(new java.awt.Color(204, 255, 255));
        lblFoto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setText("Foto");
        lblFoto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblFoto.setOpaque(true);
        lblFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFotoMouseClicked(evt);
            }
        });

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Composição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel12.setOpaque(false);

        spnQtdPecas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spnQtdPecas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        lblQtdPecas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQtdPecas.setText("Quantidade de peças");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Tipo de papel");

        boxTipoPapel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        boxTipoPapel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sulfite", "Papel de presente", "Papel espelho ou gessado", "Papel importado", "Papel Color Plus", "Nota de Dinheiro", "Papel Color Set", "Papel Metalizado", "Papel Vegetal", "Papel Kraft" }));

        boxVariacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        boxVariacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modular", "Bill Folding", "Arquitetônico", "Block Folding" }));

        dific2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dific2.setText("Variação");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(boxTipoPapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblQtdPecas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnQtdPecas, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(dific2)
                        .addGap(30, 30, 30)
                        .addComponent(boxVariacao, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dific2)
                    .addComponent(boxVariacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(boxTipoPapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnQtdPecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtdPecas))
                .addContainerGap())
        );

        panelMateriais.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Materiais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        panelMateriais.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        panelMateriais.setOpaque(false);

        chkTassel.setBackground(new java.awt.Color(255, 255, 255));
        chkTassel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkTassel.setText("Tassel de lã");

        chkPompom.setBackground(new java.awt.Color(255, 255, 255));
        chkPompom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkPompom.setText("Pompom de lã");

        chkPisca.setBackground(new java.awt.Color(255, 255, 255));
        chkPisca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkPisca.setText("Pisca-pisca");

        chkVerniz.setBackground(new java.awt.Color(255, 255, 255));
        chkVerniz.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkVerniz.setText("Verniz");

        chkCola.setBackground(new java.awt.Color(255, 255, 255));
        chkCola.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkCola.setText("Cola");

        chkNylon.setBackground(new java.awt.Color(255, 255, 255));
        chkNylon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkNylon.setText("Fio de nylon");

        chkBijuteria.setBackground(new java.awt.Color(255, 255, 255));
        chkBijuteria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkBijuteria.setText("Bijuteria");
        chkBijuteria.setToolTipText("");

        chkMandala.setBackground(new java.awt.Color(255, 255, 255));
        chkMandala.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkMandala.setText("Mandala");

        chkOutros.setBackground(new java.awt.Color(255, 255, 255));
        chkOutros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkOutros.setText("Outros");

        chkBarbante.setBackground(new java.awt.Color(255, 255, 255));
        chkBarbante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkBarbante.setText("Barbante");

        javax.swing.GroupLayout panelMateriaisLayout = new javax.swing.GroupLayout(panelMateriais);
        panelMateriais.setLayout(panelMateriaisLayout);
        panelMateriaisLayout.setHorizontalGroup(
            panelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMateriaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMateriaisLayout.createSequentialGroup()
                        .addGroup(panelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkTassel)
                            .addComponent(chkPisca)
                            .addComponent(chkPompom))
                        .addGap(33, 33, 33)
                        .addGroup(panelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMateriaisLayout.createSequentialGroup()
                                .addGroup(panelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkCola)
                                    .addComponent(chkBijuteria))
                                .addGap(2, 2, 2)
                                .addGroup(panelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelMateriaisLayout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(chkVerniz)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(chkNylon, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelMateriaisLayout.createSequentialGroup()
                                .addComponent(chkMandala)
                                .addGap(19, 19, 19)
                                .addComponent(chkBarbante)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panelMateriaisLayout.createSequentialGroup()
                        .addComponent(chkOutros)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelMateriaisLayout.setVerticalGroup(
            panelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMateriaisLayout.createSequentialGroup()
                .addGroup(panelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMateriaisLayout.createSequentialGroup()
                        .addComponent(chkTassel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMateriaisLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkBijuteria)
                            .addComponent(chkVerniz))))
                .addGroup(panelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMateriaisLayout.createSequentialGroup()
                        .addGroup(panelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkPompom)
                            .addComponent(chkCola)
                            .addComponent(chkNylon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkPisca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkOutros)
                        .addGap(18, 18, 18))
                    .addGroup(panelMateriaisLayout.createSequentialGroup()
                        .addGroup(panelMateriaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkMandala)
                            .addComponent(chkBarbante))
                        .addGap(44, 44, 44))))
        );

        btnAdicionar.setBackground(new java.awt.Color(0, 0, 102));
        btnAdicionar.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 153, 0));
        btnLimpar.setText("Cancelar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panNovoLayout = new javax.swing.GroupLayout(panNovo);
        panNovo.setLayout(panNovoLayout);
        panNovoLayout.setHorizontalGroup(
            panNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNovoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panNovoLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(panelMateriais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(48, 48, 48))
                    .addGroup(panNovoLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(panNovoLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panNovoLayout.setVerticalGroup(
            panNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNovoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(panNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMateriais, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(panNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        tbPanOrigami.addTab("Novo Origami", panNovo);

        panModular.setToolTipText("Tabela Origami Modular");
        panModular.setOpaque(false);

        tbModular.setBackground(new java.awt.Color(255, 153, 153));
        tbModular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbModular.setForeground(new java.awt.Color(51, 51, 51));
        tbModular.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Dificuldade", "Tipo de Papel", "Valor Un."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbModular.setToolTipText("Tabela Origami Modular");
        tbModular.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbModular);

        editarMod.setBackground(new java.awt.Color(0, 0, 102));
        editarMod.setFont(new java.awt.Font("Segoe Print", 1, 15)); // NOI18N
        editarMod.setForeground(new java.awt.Color(255, 255, 255));
        editarMod.setText("Editar");

        ExcluirMod.setFont(new java.awt.Font("Segoe Print", 1, 15)); // NOI18N
        ExcluirMod.setForeground(new java.awt.Color(255, 153, 0));
        ExcluirMod.setText("Excluir");
        ExcluirMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panModularLayout = new javax.swing.GroupLayout(panModular);
        panModular.setLayout(panModularLayout);
        panModularLayout.setHorizontalGroup(
            panModularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panModularLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addGroup(panModularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editarMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExcluirMod, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        panModularLayout.setVerticalGroup(
            panModularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panModularLayout.createSequentialGroup()
                .addGroup(panModularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panModularLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(editarMod)
                        .addGap(29, 29, 29)
                        .addComponent(ExcluirMod, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panModularLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        tbPanOrigami.addTab("Modular", panModular);

        panArquit.setToolTipText("Tabela Origami Arquitetônico");
        panArquit.setOpaque(false);

        tbArquit.setBackground(new java.awt.Color(204, 204, 255));
        tbArquit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbArquit.setForeground(new java.awt.Color(51, 51, 51));
        tbArquit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Dificuldade", "Tipo de Papel", "Valor Un."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbArquit.setToolTipText("Tabela Origami Arquitetônico");
        tbArquit.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbArquit);

        EditarArq.setBackground(new java.awt.Color(0, 0, 102));
        EditarArq.setFont(new java.awt.Font("Segoe Print", 1, 15)); // NOI18N
        EditarArq.setForeground(new java.awt.Color(255, 255, 255));
        EditarArq.setText("Editar");

        ExcluirArq.setFont(new java.awt.Font("Segoe Print", 1, 15)); // NOI18N
        ExcluirArq.setForeground(new java.awt.Color(255, 153, 0));
        ExcluirArq.setText("Excluir");
        ExcluirArq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirArqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panArquitLayout = new javax.swing.GroupLayout(panArquit);
        panArquit.setLayout(panArquitLayout);
        panArquitLayout.setHorizontalGroup(
            panArquitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panArquitLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(panArquitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EditarArq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExcluirArq, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        panArquitLayout.setVerticalGroup(
            panArquitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panArquitLayout.createSequentialGroup()
                .addGroup(panArquitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panArquitLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panArquitLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(EditarArq)
                        .addGap(29, 29, 29)
                        .addComponent(ExcluirArq, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        tbPanOrigami.addTab("Arquitetônico", panArquit);

        panBlock.setToolTipText("Tabela Origami Block Folding");
        panBlock.setOpaque(false);

        tbBlock.setBackground(new java.awt.Color(204, 255, 204));
        tbBlock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbBlock.setForeground(new java.awt.Color(51, 51, 51));
        tbBlock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Dificuldade", "Tipo de Papel", "Valor Un."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBlock.setToolTipText("Tabela Origami Block Folding");
        tbBlock.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbBlock);

        EditarBlock.setBackground(new java.awt.Color(0, 0, 102));
        EditarBlock.setFont(new java.awt.Font("Segoe Print", 1, 15)); // NOI18N
        EditarBlock.setForeground(new java.awt.Color(255, 255, 255));
        EditarBlock.setText("Editar");

        ExcluirBlock.setFont(new java.awt.Font("Segoe Print", 1, 15)); // NOI18N
        ExcluirBlock.setForeground(new java.awt.Color(255, 153, 0));
        ExcluirBlock.setText("Excluir");
        ExcluirBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirBlockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBlockLayout = new javax.swing.GroupLayout(panBlock);
        panBlock.setLayout(panBlockLayout);
        panBlockLayout.setHorizontalGroup(
            panBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBlockLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(panBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EditarBlock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExcluirBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        panBlockLayout.setVerticalGroup(
            panBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBlockLayout.createSequentialGroup()
                .addGroup(panBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBlockLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panBlockLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(EditarBlock)
                        .addGap(29, 29, 29)
                        .addComponent(ExcluirBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        tbPanOrigami.addTab("Block Folding", panBlock);

        panBill.setToolTipText("Tabela Origami Bill Folding");
        panBill.setOpaque(false);

        tbBill.setBackground(new java.awt.Color(153, 204, 255));
        tbBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbBill.setForeground(new java.awt.Color(51, 51, 51));
        tbBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Dificuldade", "Tipo de Papel", "Valor Un."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBill.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tbBill);

        EditarBill.setBackground(new java.awt.Color(0, 0, 102));
        EditarBill.setFont(new java.awt.Font("Segoe Print", 1, 15)); // NOI18N
        EditarBill.setForeground(new java.awt.Color(255, 255, 255));
        EditarBill.setText("Editar");

        ExcluirBill.setFont(new java.awt.Font("Segoe Print", 1, 15)); // NOI18N
        ExcluirBill.setForeground(new java.awt.Color(255, 153, 0));
        ExcluirBill.setText("Excluir");
        ExcluirBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBillLayout = new javax.swing.GroupLayout(panBill);
        panBill.setLayout(panBillLayout);
        panBillLayout.setHorizontalGroup(
            panBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBillLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(panBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EditarBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExcluirBill, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        panBillLayout.setVerticalGroup(
            panBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBillLayout.createSequentialGroup()
                .addGroup(panBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBillLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panBillLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(EditarBill)
                        .addGap(29, 29, 29)
                        .addComponent(ExcluirBill, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        tbPanOrigami.addTab("Bill Folding", panBill);

        getContentPane().add(tbPanOrigami, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 810, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gerenciar.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoMouseClicked
        JFileChooser origamiFoto = new JFileChooser();

        origamiFoto.setAcceptAllFileFilterUsed(false);
        origamiFoto.setFileFilter(new FileNameExtensionFilter("Arquivos de imagem","png","bmp","jpg","gif"));

        if(origamiFoto.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File arq = origamiFoto.getSelectedFile();
            ImageIcon img = new ImageIcon(arq.getAbsolutePath());
            resizeFoto(img);
        }
    }//GEN-LAST:event_lblFotoMouseClicked

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        String nome = txtNome.getText();
        String dific = boxDificuldade.getSelectedItem().toString();
        Float valor = Float.parseFloat(spnPreco.getValue().toString());

        String varicao = boxVariacao.getSelectedItem().toString();
        String papel = boxTipoPapel.getSelectedItem().toString();
        int qtd = Integer.parseInt(spnQtdPecas.getValue().toString());

        Icon foto = lblFoto.getIcon();

        List<String> material = new ArrayList<>();
        if(chkTassel.isSelected()) {
            material.add(chkTassel.getText());
        }
        if(chkBijuteria.isSelected()) {
            material.add(chkBijuteria.getText());
        }
        if(chkVerniz.isSelected()) {
            material.add(chkVerniz.getText());
        }
        if(chkPompom.isSelected()) {
            material.add(chkPompom.getText());
        }
        if(chkCola.isSelected()) {
            material.add(chkCola.getText());
        }
        if(chkNylon.isSelected()) {
            material.add(chkNylon.getText());
        }
        if(chkPisca.isSelected()) {
            material.add(chkPisca.getText());
        }
        if(chkMandala.isSelected()) {
            material.add(chkMandala.getText());
        }
        if(chkBarbante.isSelected()) {
            material.add(chkBarbante.getText());
        }
        if(chkOutros.isSelected()) {
            material.add(chkOutros.getText());
        }

        if( validarCampos() ) {
             // INSERIR NO BANCO
            if(gerIG.getGerDominio().nomeOrigamiExiste(nome) != null) {
                lblNome.setForeground(Color.red);      
                JOptionPane.showMessageDialog(this, "Nome já cadastrado!", "ERRO Origami", JOptionPane.ERROR_MESSAGE  );
            } else {
                try {
                    byte[] fotoBytes = FuncoesUteis.IconToBytes(foto);

                    // INSERIR
                    int id = gerIG.getGerDominio().inserirOrigami(nome, dific, valor, varicao, papel, qtd, fotoBytes, material);
                    JOptionPane.showMessageDialog(this, "Origami " + id + " inserido com sucesso.", "Inserir Origami", JOptionPane.INFORMATION_MESSAGE  );
                    limparCampos();
                } catch (HibernateException ex) {
                    JOptionPane.showMessageDialog(this, ex, "ERRO Cliente", JOptionPane.ERROR_MESSAGE  );
                }
                catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex, "ERRO Cliente", JOptionPane.ERROR_MESSAGE  );
                }
            }
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void ExcluirModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirModActionPerformed
        int rowMd = tbModular.getSelectedRow();
        
        if (rowMd != -1) {
            String elemento = (String) tbModular.getValueAt(rowMd, 0);
            Origami deletar = gerIG.getGerDominio().nomeOrigamiExiste(elemento);
            if(deletar != null) {
                gerIG.getGerDominio().excluir(deletar);
                carregarDados(tbModular, "Modular");
            }
        }
    }//GEN-LAST:event_ExcluirModActionPerformed

    private void ExcluirArqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirArqActionPerformed
        int rowAr = tbArquit.getSelectedRow();
        
        if (rowAr != -1) {
            String elemento = (String) tbArquit.getValueAt(rowAr, 0);
            Origami deletar = gerIG.getGerDominio().nomeOrigamiExiste(elemento);
            if(deletar != null) {
                gerIG.getGerDominio().excluir(deletar);
                carregarDados(tbArquit, "Arquitetônico");
            }
        }
    }//GEN-LAST:event_ExcluirArqActionPerformed

    private void ExcluirBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirBlockActionPerformed
        int rowBc = tbBlock.getSelectedRow();
        
        if (rowBc != -1) {
            String elemento = (String) tbBlock.getValueAt(rowBc, 0);
            Origami deletar = gerIG.getGerDominio().nomeOrigamiExiste(elemento);
            if(deletar != null) {
                gerIG.getGerDominio().excluir(deletar);
                carregarDados(tbBlock, "Block Folding");
            }
        } 
    }//GEN-LAST:event_ExcluirBlockActionPerformed

    private void ExcluirBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirBillActionPerformed
        int rowBi = tbBill.getSelectedRow();
        
        if (rowBi != -1) {
            String elemento = (String) tbBill.getValueAt(rowBi, 0);
            Origami deletar = gerIG.getGerDominio().nomeOrigamiExiste(elemento);
            if(deletar != null) {
                gerIG.getGerDominio().excluir(deletar);
                carregarDados(tbBill, "Bill Folding");
            }
        }
    }//GEN-LAST:event_ExcluirBillActionPerformed

    private void panelEvento() {
        tbPanOrigami.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                int selectedIndex = tbPanOrigami.getSelectedIndex();
                
                if (selectedIndex == 1) {
                    carregarDados(tbModular, "Modular");
                } else if (selectedIndex == 2) {
                    carregarDados(tbArquit, "Arquitetônico");
                } else if (selectedIndex == 3) {
                    carregarDados(tbBlock, "Block Folding");
                } else if (selectedIndex == 4) {
                    carregarDados(tbBill, "Bill Folding");
                }
            }
        });
    }
    
    private void carregarDados(JTable tabela, String condicao) {
        List<Origami> origamis = gerIG.getGerDominio().listar(Origami.class);

        DefaultTableModel tableModel = (DefaultTableModel) tabela.getModel();
        tableModel.setRowCount(0);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        tabela.setDefaultRenderer(Object.class, centerRenderer);
        
        for (Origami origami : origamis) {
            if (condicao.equals(origami.getCategoria())) {
                String nome = origami.getNome();
                String dificuldade = origami.getDificuldade();
                String papel = origami.getTipoPapel();
                float preco = origami.getPreco();
                
                String precoStr = "R$ " + Float.toString(preco);

                Object[] rowData = {nome, dificuldade, papel, precoStr};
                tableModel.addRow(rowData);
            }
        }

        tabela.setModel(tableModel);
        tabela.setShowVerticalLines(false);
    }
    
    private void resizeFoto(ImageIcon img) {
        img.setImage(img.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_DEFAULT));
        lblFoto.setText("");
        lblFoto.setIcon(img);
    }
    
    private boolean validarCampos() {
        
        String msgErro = "";
        
        lblNome.setForeground(Color.DARK_GRAY);
        lblPreco.setForeground(Color.DARK_GRAY); 
        lblQtdPecas.setForeground(Color.DARK_GRAY);
        lblFoto.setForeground(Color.DARK_GRAY);
        
        TitledBorder titledBorder = BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Materiais");
        titledBorder.setTitleFont(new java.awt.Font("Segoe UI", 0, 14));
        titledBorder.setTitleColor(Color.DARK_GRAY);
        panelMateriais.setBorder(titledBorder);
        
        if ( txtNome.getText().isEmpty() ) {
            msgErro = msgErro + "Digite um nome.\n";
            lblNome.setForeground(Color.red);            
        }
              
        float numPreco = Float.parseFloat(spnPreco.getValue().toString());
        if(numPreco == 0.00) {
            msgErro = msgErro + "Insira um preço.\n";
            lblPreco.setForeground(Color.red);  
        }
        
        int numPecas = Integer.parseInt(spnQtdPecas.getValue().toString());
        if(numPecas == 0) {
            msgErro = msgErro + "Insira uma quantidade de peças.\n";
            lblQtdPecas.setForeground(Color.red);  
        }
        
        if(lblFoto.getIcon() == null) {
            msgErro = msgErro + "Selecione uma imagem.\n";
            lblFoto.setForeground(Color.red); 
        }
        
        boolean chk_1 = chkTassel.isSelected();
        boolean chk_2 = chkBijuteria.isSelected();
        boolean chk_3 = chkVerniz.isSelected();
        boolean chk_4 = chkPompom.isSelected();
        boolean chk_5 = chkCola.isSelected();
        boolean chk_6 = chkNylon.isSelected();
        boolean chk_7 = chkPisca.isSelected();
        boolean chk_8 = chkMandala.isSelected();
        boolean chk_9 = chkBarbante.isSelected();
        boolean chk_10 = chkOutros.isSelected();
        if (!chk_1 && !chk_2 && !chk_3 && !chk_4 && !chk_5 && !chk_6 && !chk_7 && !chk_8 && !chk_9 && !chk_10) {
            msgErro = msgErro + "Selecione ao menos 1 material.\n";
            titledBorder = BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Materiais");
            titledBorder.setTitleFont(new java.awt.Font("Segoe UI", 0, 14));
            titledBorder.setTitleColor(Color.RED);
            
            panelMateriais.setBorder(titledBorder);
        }
                
        if ( msgErro.isEmpty() ) {
            return true;
        } else {            
            JOptionPane.showMessageDialog(this, msgErro, "ERRO Gerenciador", JOptionPane.ERROR_MESSAGE  );
            return false;
        }
        
    } 
    
    private void limparCampos() { 
        lblNome.setForeground(Color.DARK_GRAY);
        lblPreco.setForeground(Color.DARK_GRAY); 
        lblQtdPecas.setForeground(Color.DARK_GRAY);
        lblFoto.setForeground(Color.DARK_GRAY);
        
        TitledBorder titledBorder = BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Materiais");
        titledBorder.setTitleFont(new java.awt.Font("Segoe UI", 0, 14));
        titledBorder.setTitleColor(Color.DARK_GRAY);
        panelMateriais.setBorder(titledBorder);
        
        
        txtNome.setText( "" );
        boxDificuldade.setSelectedIndex(0);
        spnPreco.setValue(0.00);

        boxVariacao.setSelectedIndex(0);
        boxTipoPapel.setSelectedIndex(0);
        spnQtdPecas.setValue(0);

        lblFoto.setText("Foto");
        lblFoto.setIcon(null);

        chkTassel.setSelected(false);
        chkBijuteria.setSelected(false);
        chkVerniz.setSelected(false);
        chkPompom.setSelected(false);
        chkCola.setSelected(false);
        chkNylon.setSelected(false);
        chkPisca.setSelected(false);
        chkMandala.setSelected(false);
        chkBarbante.setSelected(false);
        chkOutros.setSelected(false);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarArq;
    private javax.swing.JButton EditarBill;
    private javax.swing.JButton EditarBlock;
    private javax.swing.JButton ExcluirArq;
    private javax.swing.JButton ExcluirBill;
    private javax.swing.JButton ExcluirBlock;
    private javax.swing.JButton ExcluirMod;
    private javax.swing.JComboBox<String> boxDificuldade;
    private javax.swing.JComboBox<String> boxTipoPapel;
    private javax.swing.JComboBox<String> boxVariacao;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JCheckBox chkBarbante;
    private javax.swing.JCheckBox chkBijuteria;
    private javax.swing.JCheckBox chkCola;
    private javax.swing.JCheckBox chkMandala;
    private javax.swing.JCheckBox chkNylon;
    private javax.swing.JCheckBox chkOutros;
    private javax.swing.JCheckBox chkPisca;
    private javax.swing.JCheckBox chkPompom;
    private javax.swing.JCheckBox chkTassel;
    private javax.swing.JCheckBox chkVerniz;
    private javax.swing.JLabel dific1;
    private javax.swing.JLabel dific2;
    private javax.swing.JButton editarMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblQtdPecas;
    private javax.swing.JPanel panArquit;
    private javax.swing.JPanel panBill;
    private javax.swing.JPanel panBlock;
    private javax.swing.JPanel panModular;
    private javax.swing.JPanel panNovo;
    private javax.swing.JPanel panelMateriais;
    private javax.swing.JSpinner spnPreco;
    private javax.swing.JSpinner spnQtdPecas;
    private javax.swing.JTable tbArquit;
    private javax.swing.JTable tbBill;
    private javax.swing.JTable tbBlock;
    private javax.swing.JTable tbModular;
    private javax.swing.JTabbedPane tbPanOrigami;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
