/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intergraf;

import dominio.CarrinhoCompra;
import dominio.Cliente;
import gerTarefas.GerInterGrafica;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author 2020122760226
 */
public class DlgHistorico extends javax.swing.JDialog {

    private GerInterGrafica gerIG;

    /**
     * Creates new form DlgHistorico
     */
    public DlgHistorico(java.awt.Frame parent, boolean modal, GerInterGrafica gerIG) {
        initComponents();
        this.gerIG = gerIG;
        scrollHistorico.getViewport().setOpaque(false);
        customizeTableHeader(tbHistorico);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollHistorico = new javax.swing.JScrollPane();
        tbHistorico = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        menuLoja = new javax.swing.JMenuItem();
        menuCompras = new javax.swing.JMenu();
        subMenuCarrinho = new javax.swing.JMenuItem();
        subMenuHistorico = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuExcluirConta1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollHistorico.setOpaque(false);

        tbHistorico.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tbHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cidade", "Frete", "Total", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbHistorico.setOpaque(false);
        tbHistorico.getTableHeader().setReorderingAllowed(false);
        scrollHistorico.setViewportView(tbHistorico);

        getContentPane().add(scrollHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 770, 430));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Histórico de compra");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/customer-review.png"))); // NOI18N
        menuUsuario.setText("<html><style>h1{font-size:12px}</style><h1>Usuário</h1></html>");

        menuLoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/loja-alt.png"))); // NOI18N
        menuLoja.setText("Loja de origamis");
        menuLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLojaActionPerformed(evt);
            }
        });
        menuUsuario.add(menuLoja);

        menuCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/adicionar-sacola-de-compras.png"))); // NOI18N
        menuCompras.setText("Compras");

        subMenuCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/carrinho-de-compras (1).png"))); // NOI18N
        subMenuCarrinho.setText("Carrinho de compras");
        subMenuCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCarrinhoActionPerformed(evt);
            }
        });
        menuCompras.add(subMenuCarrinho);

        subMenuHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tempo-passado.png"))); // NOI18N
        subMenuHistorico.setText("Histórico");
        menuCompras.add(subMenuHistorico);

        menuUsuario.add(menuCompras);

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/saida.png"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuUsuario.add(menuSair);
        menuUsuario.add(jSeparator3);

        menuExcluirConta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lixo.png"))); // NOI18N
        menuExcluirConta1.setText("Excluir conta");
        menuUsuario.add(menuExcluirConta1);

        jMenuBar1.add(menuUsuario);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subMenuCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCarrinhoActionPerformed
        gerIG.janelaCarrinho();
        dispose();
    }//GEN-LAST:event_subMenuCarrinhoActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        gerIG.fecharPerfil();
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLojaActionPerformed
        gerIG.janelaPedidos();
        dispose();
    }//GEN-LAST:event_menuLojaActionPerformed

    public void carregarTabela() {
        DefaultTableModel tableModel = (DefaultTableModel) tbHistorico.getModel();
        tableModel.setRowCount(0);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        tbHistorico.setDefaultRenderer(Object.class, centerRenderer);
        
        if (gerIG.getGerCliente() != null) {
            Cliente cliente = gerIG.getGerCliente();
            
            String cidade = cliente.getCidade();
            int recente = cliente.getPedidos().size() - 1;
            double frete = cliente.getPedidos().get(recente).getFrete();
            
            for(CarrinhoCompra compra : cliente.getPedidos()) {
                double total = compra.getTotal();
                String status =
            }
            String papel = origami.getTipoPapel();
            float preco = origami.getPreco();

            String precoStr = "R$ " + Float.toString(preco);

            Object[] rowData = {nome, dificuldade, papel, precoStr};
            tableModel.addRow(rowData);
        }

        tabela.setModel(tableModel);
        tabela.setShowVerticalLines(false);
    }
    
    public void customizeTableHeader(JTable table) {
        JTableHeader tableHeader = table.getTableHeader();
        
        tableHeader.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component rendererComponent = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                ((JLabel) rendererComponent).setHorizontalAlignment(SwingConstants.CENTER);
                ((JLabel) rendererComponent).setBackground(new Color(255,102,102));
                ((JLabel) rendererComponent).setForeground(Color.WHITE);
                ((JLabel) rendererComponent).setFont(new Font("Segoe Print", Font.BOLD, 16));
                
                return rendererComponent;
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu menuCompras;
    private javax.swing.JMenuItem menuExcluirConta1;
    private javax.swing.JMenuItem menuLoja;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JScrollPane scrollHistorico;
    private javax.swing.JMenuItem subMenuCarrinho;
    private javax.swing.JMenuItem subMenuHistorico;
    private javax.swing.JTable tbHistorico;
    // End of variables declaration//GEN-END:variables
}
