/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package intergraf;

import dominio.Origami;
import gerTarefas.GerInterGrafica;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author LEDS
 */
public class DlgTelaPedidos extends javax.swing.JDialog {

    private GerInterGrafica gerIG;
    /**
     * Creates new form DlgTelaPedidos
     */
    public DlgTelaPedidos(java.awt.Frame parent, boolean modal, GerInterGrafica gerIG) {
        initComponents();
        this.gerIG = gerIG;
        carregarDados(togBtnModular, "Modular");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupCategoria = new javax.swing.ButtonGroup();
        menuPopBtn = new javax.swing.JPopupMenu();
        menuPopQtd = new javax.swing.JMenuItem();
        menuPopAvaliar = new javax.swing.JMenuItem();
        menuPopAvaliacao = new javax.swing.JMenuItem();
        scrollPanelProdutos = new javax.swing.JScrollPane();
        panelProdutos = new javax.swing.JPanel();
        origami1 = new javax.swing.JToggleButton();
        tipo1 = new javax.swing.JToggleButton();
        tipo2 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        origami2 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        origami3 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        togBtnModular = new javax.swing.JToggleButton();
        togBtnBlock = new javax.swing.JToggleButton();
        togBtnBill = new javax.swing.JToggleButton();
        togBtnArquit = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAdicionarCarrinho = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        menuLoja = new javax.swing.JMenuItem();
        menuCarrinho = new javax.swing.JMenuItem();
        menuSair1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuExcluirConta1 = new javax.swing.JMenuItem();

        menuPopQtd.setText("Quantidade");
        menuPopBtn.add(menuPopQtd);

        menuPopAvaliar.setText("Avaliar");
        menuPopAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPopAvaliarActionPerformed(evt);
            }
        });
        menuPopBtn.add(menuPopAvaliar);

        menuPopAvaliacao.setText("Ver Avaliação");
        menuPopAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPopAvaliacaoActionPerformed(evt);
            }
        });
        menuPopBtn.add(menuPopAvaliacao);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Loja de Origamis");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPanelProdutos.setBorder(null);
        scrollPanelProdutos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPanelProdutos.setOpaque(false);
        scrollPanelProdutos.setViewportView(panelProdutos);

        panelProdutos.setBackground(new java.awt.Color(255, 255, 204));
        panelProdutos.setOpaque(false);

        origami1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/raposa_redimens-removebg-preview.png"))); // NOI18N
        origami1.setText("jToggleButton1");
        origami1.setComponentPopupMenu(menuPopBtn);
        origami1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        origami1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        tipo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/morango_redimens-removebg-preview.png"))); // NOI18N
        tipo1.setText("jToggleButton2");
        tipo1.setComponentPopupMenu(menuPopBtn);
        tipo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tipo1.setInheritsPopupMenu(true);
        tipo1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        tipo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/morango_redimens-removebg-preview.png"))); // NOI18N
        tipo2.setText("jToggleButton4");
        tipo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tipo2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/raposa_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton10.setText("jToggleButton3");
        jToggleButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton10.setIconTextGap(1);
        jToggleButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        origami2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/raposa_redimens-removebg-preview.png"))); // NOI18N
        origami2.setText("jToggleButton3");
        origami2.setComponentPopupMenu(menuPopBtn);
        origami2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        origami2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/morango_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton6.setText("jToggleButton2");
        jToggleButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton6.setInheritsPopupMenu(true);
        jToggleButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        origami3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/raposa_redimens-removebg-preview.png"))); // NOI18N
        origami3.setText("jToggleButton1");
        origami3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        origami3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/morango_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton9.setText("jToggleButton4");
        jToggleButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/raposa_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton7.setText("jToggleButton3");
        jToggleButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton7.setInheritsPopupMenu(true);
        jToggleButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/morango_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton8.setText("jToggleButton4");
        jToggleButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/morango_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton11.setText("jToggleButton2");
        jToggleButton11.setComponentPopupMenu(menuPopBtn);
        jToggleButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/raposa_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton12.setText("jToggleButton1");
        jToggleButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/morango_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton13.setText("jToggleButton4");
        jToggleButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/raposa_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton14.setText("jToggleButton3");
        jToggleButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton14.setInheritsPopupMenu(true);
        jToggleButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/morango_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton15.setText("jToggleButton2");
        jToggleButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/raposa_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton16.setText("jToggleButton1");
        jToggleButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelProdutosLayout = new javax.swing.GroupLayout(panelProdutos);
        panelProdutos.setLayout(panelProdutosLayout);
        panelProdutosLayout.setHorizontalGroup(
            panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProdutosLayout.createSequentialGroup()
                .addGroup(panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelProdutosLayout.createSequentialGroup()
                            .addComponent(jToggleButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(jToggleButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(jToggleButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProdutosLayout.createSequentialGroup()
                                .addComponent(origami1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(tipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(origami2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(tipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelProdutosLayout.createSequentialGroup()
                                .addComponent(origami3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelProdutosLayout.createSequentialGroup()
                        .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jToggleButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jToggleButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jToggleButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        panelProdutosLayout.setVerticalGroup(
            panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProdutosLayout.createSequentialGroup()
                .addGroup(panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(origami1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(origami2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(origami3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        scrollPanelProdutos.setViewportView(panelProdutos);

        getContentPane().add(scrollPanelProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 530));

        jPanel1.setBackground(new Color(255, 0, 200, 128));

        btnGroupCategoria.add(togBtnModular);
        togBtnModular.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        togBtnModular.setSelected(true);
        togBtnModular.setText("Modular");
        togBtnModular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togBtnModularActionPerformed(evt);
            }
        });

        btnGroupCategoria.add(togBtnBlock);
        togBtnBlock.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        togBtnBlock.setText("Block Folding");
        togBtnBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togBtnBlockActionPerformed(evt);
            }
        });

        btnGroupCategoria.add(togBtnBill);
        togBtnBill.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        togBtnBill.setText("Bill Folding");
        togBtnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togBtnBillActionPerformed(evt);
            }
        });

        btnGroupCategoria.add(togBtnArquit);
        togBtnArquit.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        togBtnArquit.setText("Arquitetônico");
        togBtnArquit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togBtnArquitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CATEGORIA DE ORIGAMI");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 102));

        btnAdicionarCarrinho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdicionarCarrinho.setForeground(new java.awt.Color(102, 0, 204));
        btnAdicionarCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shopping-cart.png"))); // NOI18N
        btnAdicionarCarrinho.setText("Adicionar ao Carrinho");
        btnAdicionarCarrinho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 204), 2, true));
        btnAdicionarCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarCarrinhoActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCELAR");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(togBtnModular, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(togBtnBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(togBtnBill, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(togBtnArquit, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdicionarCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(togBtnModular, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(togBtnBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(togBtnBill, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(togBtnArquit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdicionarCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 240, 580));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.jpg"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/customer-review.png"))); // NOI18N
        menuUsuario.setText("<html><style>h1{font-size:12px}</style><h1>Usuário</h1></html>");

        menuLoja.setText("Loja de origamis");
        menuUsuario.add(menuLoja);

        menuCarrinho.setText("Carrinho de compras");
        menuCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCarrinhoActionPerformed(evt);
            }
        });
        menuUsuario.add(menuCarrinho);

        menuSair1.setText("Sair");
        menuSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSair1ActionPerformed(evt);
            }
        });
        menuUsuario.add(menuSair1);
        menuUsuario.add(jSeparator3);

        menuExcluirConta1.setText("Excluir conta");
        menuUsuario.add(menuExcluirConta1);

        jMenuBar1.add(menuUsuario);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarCarrinhoActionPerformed
//        gerIG.janelaCarrinho();
    }//GEN-LAST:event_btnAdicionarCarrinhoActionPerformed

    private void menuSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSair1ActionPerformed
        gerIG.fecharPerfil();
    }//GEN-LAST:event_menuSair1ActionPerformed

    private void menuCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCarrinhoActionPerformed
        gerIG.janelaCarrinho();
        dispose();
    }//GEN-LAST:event_menuCarrinhoActionPerformed

    private void menuPopAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPopAvaliacaoActionPerformed
        StringBuilder mensagem = new StringBuilder();
        for (int i=0; i < 20; i++) {
            mensagem.append("Usuário tal qualquer ").append("\n");
            mensagem.append("Nota: ").append("4").append("\n");
            mensagem.append("Comentário: ").append("Não é tão bom assim e nem faz juz a imagem do produto").append("\n");
            mensagem.append("-------------------------------------\n");
            
            mensagem.append("Usuário tal qualquer ").append("\n");
            mensagem.append("Nota: ").append(i).append("\n");
            mensagem.append("Comentário: ").append("Mais vale um bebadis conhecidiss, que um alcoolatra anonimis.Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose.").append("\n");
            mensagem.append("-------------------------------------\n");
            
            mensagem.append("Usuário tal qualquer ").append("\n");
            mensagem.append("Nota: ").append(i+1).append("\n");
            mensagem.append("Comentário: ").append("Mussum Ipsum, cacilds vidis litro abertis. Diuretics paradis num copo é motivis de denguis.Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.Mais vale um bebadis conhecidiss, que um alcoolatra anonimis.Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose.").append("\n");
            mensagem.append("-------------------------------------\n");
        }
        JTextArea textArea = new JTextArea();
        textArea.setText(mensagem.toString());
        textArea.setEditable(false);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        
        
        
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setPreferredSize(new Dimension(500, 300));

        JOptionPane.showMessageDialog(this, scrollPane, "AVALIAÇÕES", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_menuPopAvaliacaoActionPerformed

    private void togBtnModularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togBtnModularActionPerformed
         carregarDados(togBtnModular, "Modular");
    }//GEN-LAST:event_togBtnModularActionPerformed

    private void togBtnBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togBtnBlockActionPerformed
        carregarDados(togBtnBlock, "Block Folding");
    }//GEN-LAST:event_togBtnBlockActionPerformed

    private void togBtnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togBtnBillActionPerformed
        carregarDados(togBtnBill, "Bill Folding");
    }//GEN-LAST:event_togBtnBillActionPerformed

    private void togBtnArquitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togBtnArquitActionPerformed
        carregarDados(togBtnArquit, "Arquitetônico");
    }//GEN-LAST:event_togBtnArquitActionPerformed

    private void menuPopAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPopAvaliarActionPerformed
        StringBuilder mensagem = new StringBuilder();
        
        JTextArea textArea = new JTextArea(5, 20);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        textArea.setFont(new java.awt.Font("Segoe UI", 1, 16));
        
        SpinnerModel spinnerModel = new SpinnerNumberModel(0, 0, 5, 1);
        
        JSpinner avaliacaoSpinner = new JSpinner(spinnerModel);
        avaliacaoSpinner.setFont(new java.awt.Font("Segoe UI", 1, 16));

        // Criação do painel
        JPanel panel = new JPanel(new GridLayout(2, 2));
        panel.add(new JLabel("Comentário:"));
//        panel.add(comentarioScroll);
        panel.add(new JLabel("Avaliação (0-5 estrelas):"));
        panel.add(avaliacaoSpinner);

        // Criação do JOptionPane personalizado
        int option = JOptionPane.showOptionDialog(
                this,
                panel,
                "Avaliação",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE,
                null,
                new String[]{"Enviar", "Cancelar"},
                "Enviar");

        // Tratamento da opção selecionada
        if (option == JOptionPane.OK_OPTION) {
            String comentario = textArea.getText();
            int avaliacao = (int) avaliacaoSpinner.getValue();
        
            mensagem.append("Comentário: " + comentario).append("\n");;
            mensagem.append("\tAvaliação: " + avaliacao).append("\n");;
            JScrollPane comentarioScroll = new JScrollPane(textArea);
            comentarioScroll.setPreferredSize(new Dimension(200, 100));

            JOptionPane.showMessageDialog(this,
                    "Comentário: " + comentario + "\n\n" +
                    "\tAvaliação: " + avaliacao + " estrela(s)",
                    "Avaliação enviada",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_menuPopAvaliarActionPerformed

    private ImageIcon redimensionarImagem(byte[] imagem) {
        byte[] imagemBytes = imagem;
        Image imagemOriginal = Toolkit.getDefaultToolkit().createImage(imagemBytes);

        int larguraDesejada = 100;
        int alturaDesejada = 110;

        Image imagemRedimensionada = imagemOriginal.getScaledInstance(larguraDesejada, alturaDesejada, Image.SCALE_SMOOTH);

        ImageIcon imagemRedimensionadaIcon = new ImageIcon(imagemRedimensionada);

        return imagemRedimensionadaIcon;
    }
    
    private void carregarDados(JToggleButton botaoSelecionado, String condicao) {
        int numColunas = 4;
        int alturaToggle = 150;
        panelProdutos.removeAll();

        List<Origami> origamis = gerIG.getGerDominio().listar(Origami.class);

        panelProdutos.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);
        gbc.anchor = new GridBagConstraints().NORTH;
        
        int rowCount = 0;
        int colCount = 0;
        
        if(botaoSelecionado.isSelected()) {
            
            for (int i = 0; i < origamis.size(); i++) {
                Origami origami = origamis.get(i);
                ImageIcon foto = redimensionarImagem(origami.getFoto());
                
                if (condicao.equals(origami.getCategoria())) {
                    JToggleButton toggleButton = new JToggleButton(origami.getNome());
                    toggleButton.setIcon(foto);
                    toggleButton.setPreferredSize(new Dimension(146, alturaToggle));
                    toggleButton.setComponentPopupMenu(menuPopBtn);
                    toggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                    toggleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                    
                    gbc.gridx = colCount;
                    gbc.gridy = rowCount;
                    panelProdutos.add(toggleButton, gbc);

                    colCount++;
                    if (colCount == numColunas) {
                        colCount = 0;
                        rowCount++;
                    }
                }
            }
        }

        panelProdutos.revalidate();
        panelProdutos.repaint();
        scrollPanelProdutos.getViewport().setOpaque(false);
//        scrollPanelProdutos.setViewportView(panelProdutos);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarCarrinho;
    private javax.swing.ButtonGroup btnGroupCategoria;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JMenuItem menuCarrinho;
    private javax.swing.JMenuItem menuExcluirConta1;
    private javax.swing.JMenuItem menuLoja;
    private javax.swing.JMenuItem menuPopAvaliacao;
    private javax.swing.JMenuItem menuPopAvaliar;
    private javax.swing.JPopupMenu menuPopBtn;
    private javax.swing.JMenuItem menuPopQtd;
    private javax.swing.JMenuItem menuSair1;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JToggleButton origami1;
    private javax.swing.JToggleButton origami2;
    private javax.swing.JToggleButton origami3;
    private javax.swing.JPanel panelProdutos;
    private javax.swing.JScrollPane scrollPanelProdutos;
    private javax.swing.JToggleButton tipo1;
    private javax.swing.JToggleButton tipo2;
    private javax.swing.JToggleButton togBtnArquit;
    private javax.swing.JToggleButton togBtnBill;
    private javax.swing.JToggleButton togBtnBlock;
    private javax.swing.JToggleButton togBtnModular;
    // End of variables declaration//GEN-END:variables
}
