/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package intergraf;

import dominio.Avaliacao;
import dominio.Cliente;
import dominio.Origami;
import gerTarefas.GerInterGrafica;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import org.hibernate.HibernateException;

/**
 *
 * @author LEDS
 */
public class DlgTelaPedidos extends javax.swing.JDialog {

    private GerInterGrafica gerIG;
    /**
     * Creates new form DlgTelaPedidos
     */
    public DlgTelaPedidos(java.awt.Frame parent, boolean modal, GerInterGrafica gerIG) {
        initComponents();
        this.gerIG = gerIG;
        carregarDados(togBtnModular, "Modularbgwr");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupCategoria = new javax.swing.ButtonGroup();
        menuPop = new javax.swing.JPopupMenu();
        popDescricao = new javax.swing.JMenuItem();
        popAvaliar = new javax.swing.JMenuItem();
        popAvaliacao = new javax.swing.JMenuItem();
        scrollPanelProdutos = new javax.swing.JScrollPane();
        panelProdutos = new javax.swing.JPanel();
        origami1 = new javax.swing.JToggleButton();
        tipo1 = new javax.swing.JToggleButton();
        tipo2 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        origami2 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        origami3 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        togBtnModular = new javax.swing.JToggleButton();
        togBtnBlock = new javax.swing.JToggleButton();
        togBtnBill = new javax.swing.JToggleButton();
        togBtnArquit = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAdicionarCarrinho = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        menuLoja = new javax.swing.JMenuItem();
        menuCarrinho = new javax.swing.JMenuItem();
        menuSair1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuExcluirConta1 = new javax.swing.JMenuItem();

        popDescricao.setText("Descrição");
        popDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popDescricaoActionPerformed(evt);
            }
        });
        menuPop.add(popDescricao);

        popAvaliar.setText("Avaliar");
        popAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popAvaliarActionPerformed(evt);
            }
        });
        menuPop.add(popAvaliar);

        popAvaliacao.setText("Ver Avaliação");
        popAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popAvaliacaoActionPerformed(evt);
            }
        });
        menuPop.add(popAvaliacao);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Loja de Origamis");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPanelProdutos.setBorder(null);
        scrollPanelProdutos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPanelProdutos.setOpaque(false);
        scrollPanelProdutos.setViewportView(panelProdutos);

        panelProdutos.setBackground(new java.awt.Color(255, 255, 204));
        panelProdutos.setOpaque(false);

        origami1.setBackground(new java.awt.Color(255, 255, 255));
        origami1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/raposa_redimens-removebg-preview.png"))); // NOI18N
        origami1.setText("jToggleButton1");
        origami1.setComponentPopupMenu(menuPop);
        origami1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        origami1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        tipo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/morango_redimens-removebg-preview.png"))); // NOI18N
        tipo1.setText("jToggleButton2");
        tipo1.setComponentPopupMenu(menuPop);
        tipo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tipo1.setInheritsPopupMenu(true);
        tipo1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        tipo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/morango_redimens-removebg-preview.png"))); // NOI18N
        tipo2.setText("jToggleButton4");
        tipo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tipo2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/raposa_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton10.setText("jToggleButton3");
        jToggleButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton10.setIconTextGap(1);
        jToggleButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        origami2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/raposa_redimens-removebg-preview.png"))); // NOI18N
        origami2.setText("jToggleButton3");
        origami2.setComponentPopupMenu(menuPop);
        origami2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        origami2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/morango_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton6.setText("jToggleButton2");
        jToggleButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton6.setInheritsPopupMenu(true);
        jToggleButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        origami3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/raposa_redimens-removebg-preview.png"))); // NOI18N
        origami3.setText("jToggleButton1");
        origami3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        origami3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/morango_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton9.setText("jToggleButton4");
        jToggleButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/raposa_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton7.setText("jToggleButton3");
        jToggleButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton7.setInheritsPopupMenu(true);
        jToggleButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/morango_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton8.setText("jToggleButton4");
        jToggleButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/morango_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton11.setText("jToggleButton2");
        jToggleButton11.setComponentPopupMenu(menuPop);
        jToggleButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/raposa_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton12.setText("jToggleButton1");
        jToggleButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/morango_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton13.setText("jToggleButton4");
        jToggleButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/raposa_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton14.setText("jToggleButton3");
        jToggleButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton14.setInheritsPopupMenu(true);
        jToggleButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/morango_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton15.setText("jToggleButton2");
        jToggleButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jToggleButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/raposa_redimens-removebg-preview.png"))); // NOI18N
        jToggleButton16.setText("jToggleButton1");
        jToggleButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelProdutosLayout = new javax.swing.GroupLayout(panelProdutos);
        panelProdutos.setLayout(panelProdutosLayout);
        panelProdutosLayout.setHorizontalGroup(
            panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProdutosLayout.createSequentialGroup()
                .addGroup(panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelProdutosLayout.createSequentialGroup()
                            .addComponent(jToggleButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(jToggleButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(jToggleButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProdutosLayout.createSequentialGroup()
                                .addComponent(origami1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(tipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(origami2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(tipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelProdutosLayout.createSequentialGroup()
                                .addComponent(origami3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelProdutosLayout.createSequentialGroup()
                        .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jToggleButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jToggleButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jToggleButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        panelProdutosLayout.setVerticalGroup(
            panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProdutosLayout.createSequentialGroup()
                .addGroup(panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(origami1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(origami2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(origami3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        scrollPanelProdutos.setViewportView(panelProdutos);

        getContentPane().add(scrollPanelProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 530));

        jPanel1.setBackground(new Color(255, 0, 200, 128));

        togBtnModular.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupCategoria.add(togBtnModular);
        togBtnModular.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        togBtnModular.setSelected(true);
        togBtnModular.setText("Modular");
        togBtnModular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togBtnModularActionPerformed(evt);
            }
        });

        togBtnBlock.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupCategoria.add(togBtnBlock);
        togBtnBlock.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        togBtnBlock.setText("Block Folding");
        togBtnBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togBtnBlockActionPerformed(evt);
            }
        });

        togBtnBill.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupCategoria.add(togBtnBill);
        togBtnBill.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        togBtnBill.setText("Bill Folding");
        togBtnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togBtnBillActionPerformed(evt);
            }
        });

        togBtnArquit.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupCategoria.add(togBtnArquit);
        togBtnArquit.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        togBtnArquit.setText("Arquitetônico");
        togBtnArquit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togBtnArquitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CATEGORIA DE ORIGAMI");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 102));

        btnAdicionarCarrinho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdicionarCarrinho.setForeground(new java.awt.Color(102, 0, 204));
        btnAdicionarCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shopping-cart.png"))); // NOI18N
        btnAdicionarCarrinho.setText("Adicionar ao Carrinho");
        btnAdicionarCarrinho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 204), 2, true));
        btnAdicionarCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarCarrinhoActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCELAR");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(togBtnModular, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(togBtnBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(togBtnBill, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(togBtnArquit, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdicionarCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(togBtnModular, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(togBtnBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(togBtnBill, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(togBtnArquit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdicionarCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 240, 575));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.jpg"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/customer-review.png"))); // NOI18N
        menuUsuario.setText("<html><style>h1{font-size:12px}</style><h1>Usuário</h1></html>");

        menuLoja.setText("Loja de origamis");
        menuUsuario.add(menuLoja);

        menuCarrinho.setText("Carrinho de compras");
        menuCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCarrinhoActionPerformed(evt);
            }
        });
        menuUsuario.add(menuCarrinho);

        menuSair1.setText("Sair");
        menuSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSair1ActionPerformed(evt);
            }
        });
        menuUsuario.add(menuSair1);
        menuUsuario.add(jSeparator3);

        menuExcluirConta1.setText("Excluir conta");
        menuUsuario.add(menuExcluirConta1);

        jMenuBar1.add(menuUsuario);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarCarrinhoActionPerformed
        List<JToggleButton> togglesSelecionados = new ArrayList<>();

        for (Component component : panelProdutos.getComponents()) {
            if (component instanceof JToggleButton) {
                JToggleButton toggleButton = (JToggleButton) component;
                if (toggleButton.isSelected()) {
                    Origami selecionado = (Origami) toggleButton.getClientProperty("origami");
                    System.out.println(selecionado.getNome() + ':' + selecionado.getDificuldade());
                }
            }
        }

        // Agora você tem a lista de toggle buttons selecionados (togglesSelecionados)

    }//GEN-LAST:event_btnAdicionarCarrinhoActionPerformed

    private void menuSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSair1ActionPerformed
        gerIG.fecharPerfil();
    }//GEN-LAST:event_menuSair1ActionPerformed

    private void menuCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCarrinhoActionPerformed
        gerIG.janelaCarrinho();
        dispose();
    }//GEN-LAST:event_menuCarrinhoActionPerformed

    private void popAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popAvaliacaoActionPerformed
        List<Avaliacao> avaliacoes = gerIG.getGerDominio().listar(Avaliacao.class);
        
        JToggleButton toggleButton = (JToggleButton) menuPop.getInvoker();
        Origami selecionado = (Origami) toggleButton.getClientProperty("origami");
        String titulo = "";
        
        StringBuilder mensagem = new StringBuilder();
        
        for (Avaliacao avaliacao : avaliacoes) {
            if(selecionado.equals(avaliacao.getOrigami())){
                titulo = "AVALIAÇÕES - " + avaliacao.getOrigami().getNome();
                if(avaliacao.getCliente() != null) {
                    mensagem.append("Usuário: ").append(avaliacao.getCliente().getNome()).append("\n");
                } else {
                    mensagem.append("Usuário: ").append("Nome qualquer").append("\n");
                }
                mensagem.append("Nota: ").append(avaliacao.getNota()).append("\n");
                mensagem.append("Comentário: ").append(avaliacao.getComentario()).append("\n");
                mensagem.append("-------------------------------------\n");
            }
        }
        JTextArea textArea = new JTextArea();
        textArea.setText(mensagem.toString());
        textArea.setEditable(false);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        
        
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setPreferredSize(new Dimension(500, 300));

        JOptionPane.showMessageDialog(this, scrollPane, titulo, JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_popAvaliacaoActionPerformed

    private void togBtnModularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togBtnModularActionPerformed
         carregarDados(togBtnModular, "Modular");
    }//GEN-LAST:event_togBtnModularActionPerformed

    private void togBtnBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togBtnBlockActionPerformed
        carregarDados(togBtnBlock, "Block Folding");
    }//GEN-LAST:event_togBtnBlockActionPerformed

    private void togBtnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togBtnBillActionPerformed
        carregarDados(togBtnBill, "Bill Folding");
    }//GEN-LAST:event_togBtnBillActionPerformed

    private void togBtnArquitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togBtnArquitActionPerformed
        carregarDados(togBtnArquit, "Arquitetônico");
    }//GEN-LAST:event_togBtnArquitActionPerformed

    private void popAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popAvaliarActionPerformed
        JTextField comentarioField = new JTextField(20);
        SpinnerModel spinnerModel = new SpinnerNumberModel(0, 0, 5, 1);
        
        JSpinner avaliacaoSpinner = new JSpinner(spinnerModel);
        avaliacaoSpinner.setFont(new java.awt.Font("Segoe UI", 1, 16));

        JPanel panel = new JPanel(new GridLayout(2, 2));
        panel.add(new JLabel("Avaliação (0-5 estrelas):"));
        panel.add(avaliacaoSpinner);
        panel.add(new JLabel("Comentário:"));
        panel.add(comentarioField);
        panel.setPreferredSize(new Dimension(200, 100));

        int option = JOptionPane.showOptionDialog(
                this,
                panel,
                "Avaliação",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE,
                null,
                new String[]{"Enviar", "Cancelar"},
                "Enviar");

        if (option == JOptionPane.OK_OPTION) {
            enviarAvalicao(comentarioField, spinnerModel);
        }
    }//GEN-LAST:event_popAvaliarActionPerformed

    private void popDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popDescricaoActionPerformed
        JToggleButton toggleButton = (JToggleButton) menuPop.getInvoker();
        Origami selecionado = (Origami) toggleButton.getClientProperty("origami");
        String titulo = "Descrição do produto - " + selecionado.getNome();

        JTextArea textArea = new JTextArea("\tValor: " + selecionado.getPreco() + "\n\n" +
                "Dificuldade: " + selecionado.getDificuldade() + "\n\n" +
                "Tipo de papel: " + selecionado.getTipoPapel() + "\n\n" +
                "Materiais complementares: " + selecionado.getMateriais());
        textArea.setEditable(false);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setPreferredSize(new Dimension(250, 150));

        JOptionPane.showMessageDialog(this, scrollPane, titulo, JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_popDescricaoActionPerformed

    private static String wrapText(String input, int maxCharactersPerLine) {
        return input.replaceAll("(.{1," + maxCharactersPerLine + "})(?:\\s|$)", "$1\n");
    }
    
    private void enviarAvalicao(JTextField comentario, SpinnerModel spinner) {
        JToggleButton toggleButton = (JToggleButton) menuPop.getInvoker();
        Origami selecionado = (Origami) toggleButton.getClientProperty("origami");

        String text = comentario.getText();
        int avaliacao = (int) spinner.getValue();
        
        Cliente cliente = null;
        
        // INSERIR NO BANCO
        try {
            // INSERIR
            int id = gerIG.getGerDominio().inserirAvalicao(cliente, selecionado, avaliacao, text);
            
            String wrappedText = wrapText(text, 70);
            JTextArea textArea = new JTextArea("\tAvaliacao " + id + " inserida com sucesso.\n\n" +
                    "Avaliação: " + avaliacao + " estrela(s)" + "\n\n" +
                    "Comentário: " + wrappedText);
            textArea.setEditable(false);
            textArea.setLineWrap(true);
            textArea.setWrapStyleWord(true);

            JScrollPane scrollPane = new JScrollPane(textArea);
            scrollPane.setPreferredSize(new Dimension(300, 150));
            
            
            JOptionPane.showMessageDialog(this, scrollPane, "Inserir Avalicao", JOptionPane.INFORMATION_MESSAGE  );
        } catch (HibernateException ex) {
            JOptionPane.showMessageDialog(this, ex, "ERRO Avaliacao", JOptionPane.ERROR_MESSAGE  );
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex, "ERRO Avaliacao", JOptionPane.ERROR_MESSAGE  );
        }
    }
    
    private ImageIcon redimensionarImagem(byte[] imagem) {
        byte[] imagemBytes = imagem;
        Image imagemOriginal = Toolkit.getDefaultToolkit().createImage(imagemBytes);

        int larguraDesejada = 100;
        int alturaDesejada = 110;

        Image imagemRedimensionada = imagemOriginal.getScaledInstance(larguraDesejada, alturaDesejada, Image.SCALE_SMOOTH);

        ImageIcon imagemRedimensionadaIcon = new ImageIcon(imagemRedimensionada);

        return imagemRedimensionadaIcon;
    }
    
    private void carregarDados(JToggleButton botaoSelecionado, String condicao) {
        int numColunas = 4;
        int alturaToggle = 150;
        panelProdutos.removeAll();

        List<Origami> origamis = gerIG.getGerDominio().listar(Origami.class);

        panelProdutos.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);
        gbc.anchor = new GridBagConstraints().NORTH;
        
        int rowCount = 0;
        int colCount = 0;
        
        if(botaoSelecionado.isSelected()) {
            
            for (int i = 0; i < origamis.size(); i++) {
                Origami origami = origamis.get(i);
                ImageIcon foto = redimensionarImagem(origami.getFoto());
                
                if (condicao.equals(origami.getCategoria())) {
                    JToggleButton toggleButton = new JToggleButton(origami.getNome());
                    toggleButton.setBackground(new java.awt.Color(255, 255, 255));
                    toggleButton.setIcon(foto);
                    toggleButton.setPreferredSize(new Dimension(146, alturaToggle));
                    toggleButton.setComponentPopupMenu(menuPop);
                    toggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                    toggleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                    
                    toggleButton.putClientProperty("origami", origami);
                    
                    gbc.gridx = colCount;
                    gbc.gridy = rowCount;
                    panelProdutos.add(toggleButton, gbc);

                    colCount++;
                    if (colCount == numColunas) {
                        colCount = 0;
                        rowCount++;
                    }
                }
            }
        }

        panelProdutos.revalidate();
        panelProdutos.repaint();
        scrollPanelProdutos.getViewport().setOpaque(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarCarrinho;
    private javax.swing.ButtonGroup btnGroupCategoria;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JMenuItem menuCarrinho;
    private javax.swing.JMenuItem menuExcluirConta1;
    private javax.swing.JMenuItem menuLoja;
    private javax.swing.JPopupMenu menuPop;
    private javax.swing.JMenuItem menuSair1;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JToggleButton origami1;
    private javax.swing.JToggleButton origami2;
    private javax.swing.JToggleButton origami3;
    private javax.swing.JPanel panelProdutos;
    private javax.swing.JMenuItem popAvaliacao;
    private javax.swing.JMenuItem popAvaliar;
    private javax.swing.JMenuItem popDescricao;
    private javax.swing.JScrollPane scrollPanelProdutos;
    private javax.swing.JToggleButton tipo1;
    private javax.swing.JToggleButton tipo2;
    private javax.swing.JToggleButton togBtnArquit;
    private javax.swing.JToggleButton togBtnBill;
    private javax.swing.JToggleButton togBtnBlock;
    private javax.swing.JToggleButton togBtnModular;
    // End of variables declaration//GEN-END:variables
}
