/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package intergraf;

import gerTarefas.GerInterGrafica;

/**
 *
 * @author LEDS
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private GerInterGrafica gerIG;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(GerInterGrafica gerIG) {
        initComponents();
        this.gerIG = gerIG;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnGerenciador = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal De Simulação");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Escolha a sua modalidade:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("<html> <style>h3{font-size: 15px} h1{font-size: 30px; text-align:center} </style> <h3>Bem vindo ao sistema de simulação</h3> <h1>OrigamiCraft</h1> </html>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        btnGerenciador.setBackground(new java.awt.Color(153, 153, 255));
        btnGerenciador.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btnGerenciador.setForeground(new java.awt.Color(255, 255, 255));
        btnGerenciador.setText("GERENCIADOR");
        btnGerenciador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerenciador, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 180, 40));

        btnCliente.setBackground(new java.awt.Color(153, 153, 255));
        btnCliente.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCliente.setText("CLIENTE");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 130, 40));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        gerIG.janelaLogInCliente();
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnGerenciadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciadorActionPerformed
        gerIG.janelaGerenciar();
    }//GEN-LAST:event_btnGerenciadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnGerenciador;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
